# Every file below is wrapped in its own named @testset and depends only on
# ../fixtures.jl, so any file can be run standalone (include fixtures.jl first)
# and the include order is free.
include("fixtures.jl")
include("core/dsl_static_models_and_backend.jl")
include("core/dist_exponential_poisson.jl")
include("core/dist_gamma_studentt.jl")
include("core/dist_beta_categorical.jl")
include("core/dist_inversegamma_weibull_binomial.jl")
include("core/dist_laplace_geometric_negbinom.jl")
include("core/dist_dirichlet.jl")
include("core/dist_mvnormal_diag.jl")
include("core/vector_backend_sampler.jl")
include("core/batched_advi_particle.jl")
include("core/tempered_batched_smc.jl")
include("core/proposal_diagnostics_overflow.jl")
include("core/tuple_and_loop_addresses.jl")
include("core/integrator_nuts_proposal.jl")
include("core/nuts_uturn_turning.jl")
include("core/warmup_driver_regression.jl")
include("core/mcmc_diagnostics_ess_mcse.jl")
include("core/batched_scoring_eltype_f32.jl")
include("core/predictive_sampling_smc_resampling.jl")
include("core/waic_psis_loo.jl")
include("core/map_laplace_approximation.jl")
include("core/per_chain_warmup_batched.jl")
include("core/dense_mass_matrix_single_chain.jl")
include("core/dist_truncated.jl")
include("core/device_lowering_parity.jl")
include("core/dist_mixture.jl")
include("core/device_gradient_dual.jl")
include("core/vectorized_obs_iid_latents.jl")
include("core/device_hmc_advi.jl")
include("core/dist_mvnormal_dense.jl")
include("core/masked_batched_nuts.jl")
include("core/dist_lkj_cholesky.jl")
include("core/backend_native_families.jl")
include("core/device_masked_nuts.jl")
