include("batched/workspace.jl")
include("batched/manual_gradient.jl")
include("batched/gradients/core.jl")
include("batched/gradients/continuous.jl")
include("batched/gradients/discrete.jl")
include("batched/gradients/structured.jl")
include("batched/gradients/truncated.jl")
include("batched/api.jl")
